spring:
  config:
    import:
      - classpath:/config/datasource-local.yml

logging:
  file:
    name: logs/authentication.log
  logback:
    rolling policy:
      max-history: 10
      max-file-size: 500MB
  level:
    root: info
    org.msa.authenticationserver: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka